
CREATE OR REPLACE TABLE User_tbl
(
    id INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    account NVARCHAR(40) NOT NULL
   
   
);
CREATE OR REPLACE  UNIQUE INDEX IPK_User_ID ON User_tbl(id);

CREATE OR REPLACE  TABLE Mobile_tbl
(
    id INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    number NVARCHAR(40) NOT NULL,
    used CHAR(1) NOT NULL,
	version TIMESTAMP NOT NULL
   
);
CREATE OR REPLACE  INDEX IPK_Number_ID ON Mobile_tbl(id);

CREATE OR REPLACE  TABLE Service_tbl
(
    id INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name NVARCHAR(40) NOT NULL
  

   
);
CREATE OR REPLACE  INDEX IPK_Service_ID ON Service_tbl(id);


CREATE OR REPLACE  TABLE User_Mobile_tbl
(
    id INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    user_id INTEGER NOT NULL,
  	mobile_id INTEGER NOT NULL,
  	status CHAR(1) NOT NUll,
	created TIMESTAMP NOT NULL 
   
);
CREATE OR REPLACE  INDEX IPK_User_Mobile_Mobile ON User_Mobile_tbl(mobile_id);


CREATE OR REPLACE  TABLE User_Mobile_Service_tbl
(
    id INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    user_mobile_id INTEGER NOT NULL,
  	service_id INTEGER NOT NULL,
  	status CHAR(1) NOT NUll,
	created TIMESTAMP NOT NULL
   
);
CREATE OR REPLACE  INDEX IPK_User_Mobile_Service_Rel ON User_Mobile_Service_tbl(user_mobile_id);

CREATE OR REPLACE TABLE lock (
    id INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    lock_key varchar(255) unique,
    token varchar(255),
    expireAt timestamp,
);



insert into User_tbl (account) values ('account_1');
insert into User_tbl (account) values ('account_2');
insert into User_tbl (account) values ('account_3');

insert into Mobile_tbl (number,used,version) values ('95555555','0','2018-11-25 00:00:00');
insert into Mobile_tbl (number,used,version) values ('96666666','0','2018-11-25 00:00:00');
insert into Mobile_tbl (number,used,version) values ('97777777','0','2018-11-25 00:00:00');
insert into Mobile_tbl (number,used,version) values ('98888888','0','2018-11-25 00:00:00');
insert into Mobile_tbl (number,used,version) values ('99999999','0','2018-11-25 00:00:00');

insert into Service_tbl (name) values ('Roaming');
insert into Service_tbl (name) values ('Redirecting');
insert into Service_tbl (name) values ('Caller Display');
insert into Service_tbl (name) values ('Others');

